controller_list:
  - name: fake_L_xarm_controller
    joints:
      - L_joint1
      - L_joint2
      - L_joint3
      - L_joint4
      - L_joint5
      - L_joint6
  - name: fake_R_xarm_controller
    joints:
      - R_joint1
      - R_joint2
      - R_joint3
      - R_joint4
      - R_joint5
      - R_joint6
  - name: fake_xrams_controller
    joints:
      - L_joint1
      - L_joint2
      - L_joint3
      - L_joint4
      - L_joint5
      - L_joint6
      - R_joint1
      - R_joint2
      - R_joint3
      - R_joint4
      - R_joint5
      - R_joint6
  - name: fake_L_gripper_controller
    joints:
      - L_drive_joint
  - name: fake_R_gripper_controller
    joints:
      - R_drive_joint
initial:  # Define initial robot poses.
  - group: L_xarm
    pose: home
  - group: R_xarm
    pose: home
  - group: xrams
    pose: home
  - group: L_gripper
    pose: open
  - group: R_gripper
    pose: open