# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: L_xarm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - L_joint1
    - L_joint2
    - L_joint3
    - L_joint4
    - L_joint5
    - L_joint6
    - L_drive_joint
    - R_joint1
    - R_joint2
    - R_joint3
    - R_joint4
    - R_joint5
    - R_joint6
    - R_drive_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: L_xarm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - L_joint1
      - L_joint2
      - L_joint3
      - L_joint4
      - L_joint5
      - L_joint6
  - name: R_xarm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - R_joint1
      - R_joint2
      - R_joint3
      - R_joint4
      - R_joint5
      - R_joint6
  - name: L_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - L_drive_joint
  - name: R_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - R_drive_joint
L_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - L_drive_joint
  gains:
    L_drive_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_left_finger_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_left_inner_knuckle_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_right_outer_knuckle_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_right_finger_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_right_inner_knuckle_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
R_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - R_drive_joint
  gains:
    R_drive_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_left_finger_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_left_inner_knuckle_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_right_outer_knuckle_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_right_finger_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_right_inner_knuckle_joint: {p: 30.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
L_xarm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - L_joint1
    - L_joint2
    - L_joint3
    - L_joint4
    - L_joint5
    - L_joint6
  gains:
    L_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
R_xarm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - R_joint1
    - R_joint2
    - R_joint3
    - R_joint4
    - R_joint5
    - R_joint6
  gains:
    R_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
